# Generated by Django 5.1.2 on 2024-10-28 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to='images')),
                ('bio', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('social_media_link', models.URLField(blank=True)),
                ('interests', models.TextField(blank=True)),
                ('languages', models.CharField(blank=True, max_length=255)),
                ('references', models.TextField(blank=True)),
                ('work_experience', models.TextField(blank=True)),
                ('education_background', models.TextField(blank=True)),
                ('personal_skills', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
