# Generated by Django 5.1.2 on 2024-10-28 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_profile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='references',
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='company_profile')),
                ('background_photo', models.ImageField(blank=True, null=True, upload_to='company_background')),
                ('location', models.CharField(max_length=250)),
                ('activity_scope', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('website', models.URLField(blank=True, max_length=250, null=True)),
                ('established_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-established_at'],
                'indexes': [models.Index(fields=['-established_at'], name='account_com_establi_396f9b_idx')],
            },
        ),
    ]
