# Generated by Django 5.1.2 on 2024-10-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_profile_references_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='manager',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='company',
            name='background_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/company_background'),
        ),
        migrations.AlterField(
            model_name='company',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/company_profile'),
        ),
    ]
