# Generated by Django 5.1.2 on 2024-11-02 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_manager_company_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='background_photo',
            field=models.ImageField(blank=True, null=True, upload_to='company_background'),
        ),
        migrations.AlterField(
            model_name='company',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='company_profile'),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=255, unique_for_date='anounced_at')),
                ('salary', models.IntegerField()),
                ('agreement_duration', models.CharField(blank=True, max_length=250, null=True)),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=10)),
                ('education', models.CharField(choices=[('U', 'UnderGraduate'), ('B', 'Bachelor'), ('M', 'Master'), ('P', 'PHD'), ('N', 'Not Required')], default='N', max_length=20)),
                ('required_experience', models.CharField(blank=True, max_length=250, null=True)),
                ('end_of_convenant', models.DateField()),
                ('anounced_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=250)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company', to='account.company')),
            ],
            options={
                'ordering': ['-anounced_at'],
                'indexes': [models.Index(fields=['-anounced_at'], name='account_job_anounce_a132b7_idx')],
            },
        ),
    ]
