# Generated by Django 5.1.2 on 2024-11-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_company_email_alter_company_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-announced_at']},
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='account_job_anounce_a132b7_idx',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='anounced_at',
            new_name='announced_at',
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(max_length=255, unique_for_date='announced_at'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['-announced_at'], name='account_job_announc_401296_idx'),
        ),
    ]
