# Generated by Django 5.1.2 on 2024-11-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_job_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['title']},
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='account_job_announc_401296_idx',
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(),
        ),
    ]
