# Generated by Django 5.1.2 on 2024-11-13 16:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestions',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
