# Generated by Django 5.1.2 on 2024-11-13 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_suggestions_submit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestions',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announced_jobs', to='account.job'),
        ),
    ]
