# Generated by Django 5.1.2 on 2024-11-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='suggested_number_of',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
