# Generated by Django 5.1.2 on 2024-11-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_ratingcompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestions',
            name='languages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
